name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      
      - 
        name: Replace placeholders
        run: |
          sed -i "s/{{PLACEHOLDER1}}/${{ secrets.PLACEHOLDER1 }}/g" .config/config.go
          sed -i "s/{{PLACEHOLDER2}}/${{ secrets.PLACEHOLDER2 }}/g" .config/config.go

      - name: Move config.go to config directory
        run: |
          mkdir -p config
          mv .config/config.go config/config.go

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
